# Generated by Django 2.2.7 on 2020-03-19 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('keyfile', models.FileField(upload_to='key/%Y/%m', verbose_name='上传加密文件')),
                ('productId', models.CharField(max_length=128, verbose_name='版权上链id')),
                ('owner_address', models.CharField(max_length=42, verbose_name='版权拥有者地址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
