# Generated by Django 2.2.7 on 2020-03-19 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('purchase_bcId', models.CharField(max_length=128, unique=True, verbose_name='购买凭证id')),
                ('key_ipfsHash', models.CharField(max_length=64, verbose_name='密钥ipfs hash')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
