# Generated by Django 2.2.7 on 2020-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_uploadkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadkey',
            name='upload_key',
            field=models.FileField(default='', upload_to='upload_key/%Y/%m', verbose_name='上传至ipfs文件'),
        ),
    ]
