# Generated by Django 2.2.7 on 2020-03-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_uploadkey_upload_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadkey',
            name='upload_key',
        ),
    ]
