# Generated by Django 2.2.7 on 2020-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_uploadkey_upload_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadkey',
            name='transactionHash',
            field=models.CharField(default='', max_length=128, verbose_name='交易hash'),
        ),
    ]
