# Generated by Django 2.2.7 on 2020-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200319_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadkey',
            name='address',
            field=models.CharField(default='', max_length=42, unique=True, verbose_name='账户地址'),
        ),
        migrations.AddField(
            model_name='uploadkey',
            name='public',
            field=models.CharField(default='', max_length=130, verbose_name='账户公钥'),
        ),
    ]
