# Generated by Django 2.2.7 on 2020-04-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20200412_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadkey',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
