# Generated by Django 2.2.7 on 2020-04-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_uploadkey_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadkey',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.ReceiveKey', verbose_name='购买的版权'),
        ),
    ]
