# Generated by Django 2.2.7 on 2020-04-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20200412_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadkey',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态0还在排队1已上链但未通知主系统2全部完成'),
        ),
    ]
