# Generated by Django 2.2.7 on 2020-04-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20200420_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_db',
            new_name='Key_db_one',
        ),
    ]
