# Generated by Django 2.2.7 on 2020-04-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20200420_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_db_one',
            new_name='Key_db_two',
        ),
    ]
