# Generated by Django 2.2.7 on 2020-04-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auto_20200420_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_db_two',
            new_name='Key_db_three',
        ),
    ]
