# Generated by Django 2.2.7 on 2020-04-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20200420_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_db_four',
            new_name='Key_db_five',
        ),
    ]
