# Generated by Django 2.2.7 on 2020-04-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20200420_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key_db_five',
            options={'managed': False},
        ),
    ]
