# Generated by Django 2.2.7 on 2020-04-20 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20200420_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_db_four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('key', models.CharField(max_length=128, verbose_name='分割密钥')),
                ('productId', models.CharField(max_length=128, verbose_name='版权上链id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Key_db_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('key', models.CharField(max_length=128, verbose_name='分割密钥')),
                ('productId', models.CharField(max_length=128, verbose_name='版权上链id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Key_db_three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('key', models.CharField(max_length=128, verbose_name='分割密钥')),
                ('productId', models.CharField(max_length=128, verbose_name='版权上链id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Key_db_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('key', models.CharField(max_length=128, verbose_name='分割密钥')),
                ('productId', models.CharField(max_length=128, verbose_name='版权上链id')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
