# Generated by Django 2.2.7 on 2020-04-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_key_db_four_key_db_one_key_db_three_key_db_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadkey',
            name='productId',
            field=models.CharField(default='', max_length=128, verbose_name='版权上链id'),
        ),
    ]
